language: java
jdk: openjdk8
branches:
  only:
  - main
  - "/.*-[0-9]+\\..*/"
install: true
script:
- ".travis/build.sh"
cache:
  directories:
  - "~/.m2/repository"
env:
  global:
    secure: FDyoYHvurPJe0vrsprM3qu0yQa8fwpejMSJRtVvlhXxGzsbgGoi969bH/w/l/M2BwYRAHbqZpVF758vwjxcCUbmuUXDxaWxbNSIhUJci07LyuCUnFDS70EGkoOKycz05O2xGIb3jpJHAuYp4RqZWvtVKgbH7C0r0zP9mz5jeTzyeIXb3qJNRJQhyVNMrvu3w8anJ4wNTXtOHt+J55WoSWFvCciUaq+4xrz6+zCmi1TxBtOfyR2lEjl+onh0J/qBl0PlXOzQruYEZquWUhiVgs134ke0Iuh5Ied5T7gI00PHI2U63bL50fDMk8MJXH1AvXSIBhdQFqxcVDwQUT3JRz0en8uzyaczKWH9unC3KzRMJOWT//6ZWroywtqqk97VY4I+EGmY8zYY7nXHMwtXeaUaQCRr9sJd+fKmKMBzTL1PWT9uBmgyGc89hkkgwvjWfA0tHOR8gc4BpQwImG6J4oLq1H0C0bOMVK9lHnRMzutOaoi3fzY+0VSrKYJwlVR1CLZJyZQhViqrMXaEmxa3TwNFUlFmm0ysamFiDNOsnBHdCDOX8Cpw6BEcLaMVAXz29jevhsJXnAaDORtiy7bgFTSjvp4cS73D2WbIcYFgA61ypw58t4LgZxPi5JwkZFVXwHD62qF58FJbD0J1vkKq2jFckyVSrLhgueKplvHIZkMQ=
